FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
  gcc curl vim less jq git rsync

RUN curl -sSL https://get.docker.com | sh
RUN pip install --upgrade pip
RUN pip install conducto redis

WORKDIR /usr/conducto-demo
COPY . .

CMD ["/bin/bash"]
